# Generated by Django 4.1.5 on 2023-01-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0053_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postid',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplication.post'),
            preserve_default=False,
        ),
    ]
